version: '3.3'

services:
  apache:
    #servidor de apache n.1
    image: httpd:latest #imagen del contenedor
    volumes:
      - ./datos/web/reto-intemodular-clima-main:/usr/local/apache2/htdocs/ #a que documento hace referencia
    ports:
      #puertos
      - "8081:80"

  nginx:
    image: nginx:latest
    volumes:
      - ./datos/nginx.conf:/etc/nginx/nginx.conf #archivo de configuracion para este servidor
    ports:
      - "8080:80"

  alimentador:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8085:8000'
    environment:
      - DB_HOST=172.17.0.1
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
      - DB_DATABASE=EuskoClima
    volumes:
      - './datos/alimentador:/app'

  euskoclima-api:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8086:8000'
    environment:
      - DB_HOST=172.17.0.1
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
      - DB_DATABASE=EuskoClima
    volumes:
      - './datos/euskoclima-api:/app'

  mysql:
    image: mysql:latest
    container_name: MySql
    environment:
      MYSQL_DATABASE: 'EuskoClima'
      MYSQL_USER: 'Oier'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './my-db:/var/lib/mysql'
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8087:80'
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=12345678
